import {createElement} from 'lwc';
import MeetingRooms from 'c/meetingRooms';

describe('c-meeting-rooms', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-meeting-rooms', {
            is: MeetingRooms
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });

    it('count of meeting rooms should be 7' , () => {
        //created a virtual DOM
        const meetingRooms = createElement('c-meetingRooms', {is:MeetingRooms});
        
        document.body.appendChild(meetingRooms);

        const allMeetingRoomComponents = meetingRooms.shadowRoot.querySelectorAll('c-meetingRooms');

        expect(allMeetingRoomComponents.length).toBe(7);
    });

    it("title should be Meeting Rooms", () => {
        const meetingRooms = createElement("c-meetingRooms", {is:MeetingRooms});

        const lightningCard = meetingRooms.shadowRoot.querySelector("lightning-card");

        debugger;
        expect(lightningCard.title).toBe("Meeting Rooms");
    });
});